
def formularios():
    print('************************')
    print('Formulário - Recurso JARI')
    condinf = int(input('Você é: (1) condutor ou (2) proprietário do  veículo?'))
    if (condinf == 1 or condinf == 2):
        print('************************')
        print('Dados Pessoais')
        print('************************')
        requerente = input('Nome do requerente: ')
        identidade = int(input('Número da identidade (Ex.: 3344123): '))
        email = input('E-mail: ')
        orgaorg = input('Orgão emissor: ')
        cpf = int(input('Número do CPF: '))
        cnh = int(input('Número do registro da CNH: '))
        ufcnh = input('UF da CNH: ')
        print('************************')
        print('Dados Pessoais')
        print('************************')
        cep = int(input('CEP: '))
        endereco = input('Endereço: ')
        bairro = input('Bairro: ')
        cidade = input('Cidade: ')
        ufcidade = input('UF: ')
        print('************************')
        print('Dados sobre infração e veículo')
        print('************************')
        placa = int(input('Placa do veículo: '))
        ufplaca = int(input('UF da placa: '))
        autoinfr = input('Digite o Auto de infração: ')
        argumentos = input('Venho à presença de Vossa Senhoria, interpor Recurso Administrativo de Trânsito, nos termos do artigo 285 do Código de Trânsito Brasileiro e Resoluções Contran nº 299/2008 e 619/2016, do auto de infração citado acima, pelas razões e fatos expostos a seguir: ')
        print("Recurso enviado, obrigado!")
    else:
        print('Opção inválida! Tente novamente.')
        formularios()